Vagrant.configure(2) do |config|
  config.vm.define 'txt-etl' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'etl'
      box.vm.network :private_network, ip: "192.168.11.2"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "2048"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      config.vm.provision "shell", path: "installETL.bash"
  end
end
