ENV["LC_ALL"] = "en_US.UTF-8"

bindIP = '192.168.10.2'

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox"
  config.vm.hostname= "ipa.example.org"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.box = 'ubuntu/xenial64'

  config.vm.provider :virtualbox do |vb,override|
     vb.customize ["modifyvm", :id, "--memory", "2048"]
     vb.customize ["modifyvm", :id, "--cpus", "1"]
     override.vm.network :private_network, ip: "192.168.10.2"
     override.vm.synced_folder ".", "/vagrant", disabled: false
   end

   config.vm.provider :aws do |aws, override|
     aws.access_key_id = ENV['AWS_KEY']
     aws.secret_access_key = ENV['AWS_SECRET']
     aws.keypair_name = ENV['AWS_KEYNAME']
     aws.instance_type = "t2.micro"
     aws.region = "us-east-1"
     aws.ami = "ami-772aa961"
     override.ssh.username = 'ubuntu'
     override.ssh.private_key_path = ENV['AWS_KEYPATH']

   end

   config.vm.provision "shell", path: "install-freeipa.bash", args: "#{bindIP}"

end
