Vagrant.configure(2) do |config|
  config.vm.define 'osse' do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = 'osse-singlebox'
      box.vm.network :private_network, ip: "192.168.11.2"
      box.vm.provider :virtualbox do |vb|
       vb.customize ["modifyvm", :id, "--memory", "4096"]
       vb.customize ["modifyvm", :id, "--cpus", "2"]
      end
      config.vm.provision "shell", path: "install-OSSE-singlebox.bash"
  end
end
